version: "3.0"
services:
  php:
    build:
      context: "./configs/php"
      dockerfile: "./Dockerfile"
    restart: "always"
    volumes:
      - "./src:/code"
    links:
      - mysql
  nginx:
    build:
      context: "./configs/nginx"
      dockerfile: "./Dockerfile"
    restart: "always"
    ports:
      - "8080:80"
    volumes:
      - "./src:/code"
    links:
      - php
  mysql:
    image: "mysql:8.0.3"
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: secret